## Включение увлажнения
- alias: 07_dd_hum_auto_on
#  initial_state: true
  initial_state: false
## ТРИГГЕР !!!
  trigger:
## Проверка каждые 5 минут
   - platform: time_pattern
     minutes: '/5'
## Закрытие окна  
   - platform: state
     entity_id: binary_sensor.door_window_sensor_158d0001193697
     from: 'on'
     to: 'off'
## Закрытие двери
   - platform: state
     entity_id: binary_sensor.door_window_sensor_158d00015843d4
     from: 'on'
     to: 'off'
## УСЛОВИЯ !!!
  condition:
## Увлажнитель выключен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'off'
## Влажность ниже 45 %
     - condition: numeric_state
       entity_id: sensor.humidity_158d000156e92e
       below: 45
## Время работы
     - condition: time
       after: '08:00:00'
       before: '21:59:00'
## Закрыто окно
     - condition: state
       entity_id: binary_sensor.door_window_sensor_158d0001193697
       state: 'off'
## Закрыта дверь на балкон
     - condition: state
       entity_id: binary_sensor.door_window_sensor_158d00015843d4
       state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.plug_158d000114a1e1

## Выключение увлажнения    
- alias: 07_dd_hum_auto_off
#  initial_state: true
  initial_state: false
  trigger:
## Влажность выше 55 %
   - platform: numeric_state
     entity_id: sensor.humidity_158d000156e92e
     above: 55
## Открыто окно
   - platform: state
     entity_id: binary_sensor.door_window_sensor_158d0001193697
     from: 'off'
     to: 'on'
## Открыта дверь на балкон
   - platform: state
     entity_id: binary_sensor.door_window_sensor_158d00015843d4
     from: 'off'
     to: 'on'
## 10 часов вечера
   - platform: time
     at: '22:00:00'
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'on'
  action:
  - service: switch.turn_off
    entity_id: switch.plug_158d000114a1e1
    
## Предупреждение о недостатке воды
- alias: 07_dd_hum_water_warning
#  initial_state: true
  initial_state: false
  trigger:
## Падение мощности менее 10 Ватт
   - platform: numeric_state
     entity_id: sensor.load_158d000114a1e1
     below: 10
  condition:
## Увлажнитель включен
     - condition: state
       entity_id: switch.plug_158d000114a1e1
       state: 'on'
## Время работы
     - condition: time
       after: '08:00:00'
       before: '21:59:00'
  action:
    - service: notify.telegram
      data:
        title: 'Отчет'
        message: "Детская Д, в увлажнителе кончилась вода, или он отключен вручную, время - {{ states('sensor.time_date') }}"